[GLOBAL]
pikesquares_version = "0.1.3"

[python]
enable_resolves = true
interpreter_constraints = [">=3.11"]

# We generate this via cargo run -p package -- --update-lock.
resolves_generate_lockfiles = false

[python.resolves]
python-default = "tools/lock.json"

[python-infer]
use_rust_parser = true

[pex-cli]
version = "v2.1.137"
known_versions = [
    "v2.1.137|macos_arm64 |faad51a6a108fba9d40b2a10e82a2646fccbaf8c3d9be47818f4bffae02d94b8|4098329",
    "v2.1.137|macos_x86_64|faad51a6a108fba9d40b2a10e82a2646fccbaf8c3d9be47818f4bffae02d94b8|4098329",
    "v2.1.137|linux_x86_64|faad51a6a108fba9d40b2a10e82a2646fccbaf8c3d9be47818f4bffae02d94b8|4098329",
    "v2.1.137|linux_arm64 |faad51a6a108fba9d40b2a10e82a2646fccbaf8c3d9be47818f4bffae02d94b8|4098329",
]

[subprocess-environment]
env_vars = [
    "BUILDROOT=%(buildroot)s"
]

[source]
root_patterns = [
    "/tools",
    "/tools/src",
    "/tools/tests",
    "/tools/test_support",
]
