[lift]
name = "scie-pikesquares"
description = "PikeSquares isolation."
#base = "{scie.env.SCIE_BASE:/var/lib/pikesquares}"
load_dotenv = true

[lift.app_info]
repo = "https://github.com/eloquentbits/scie-pikesquares"

[lift.ptex]
id = "ptex"
version = "1.2.0"
argv1 = "{scie.env.PIKESQUARES_BOOTSTRAP_URLS={scie.lift}}"

[lift.scie_jump]
version = "1.2.0"

[[lift.interpreters]]
id = "cpython"
provider = "PythonBuildStandalone"
release = "20241002"
lazy = true
version = "3.12.7"

#[[lift.interpreters]]
#id = "cpython39"
#provider = "PythonBuildStandalone"
#release = "20241007"
#lazy = true
#version = "3.9.18"

#[[lift.interpreter_groups]]
#id = "cpython"
#selector = "{scie.bindings.configure:PYTHON}"
#members = [
#    "cpython39",
#    "cpython312",
#]

[[lift.files]]
# N.B.: We name the scie-pikesquares binary scie-pikesquares.bin since the scie itself is named scie-pikesquares
# which would conflict when packaging.
name = "scie-pikesquares.bin"

[[lift.files]]
name = "tools.pex"

[[lift.files]]
name = "uwsgi/uwsgi"
key = "uwsgi_bin"

##################################################################
################### uv
[[lift.files]]
name = "uv-macos-x86_64"
key = "uv-x86_64-apple-darwin"
type = "tar.gz"
digest = { size = 81373, fingerprint = "f879864954b2229611155bb201088d0f09becf1436b0ec8707c8f560e98e9209" }
source = { url = "https://github.com/astral-sh/uv/releases/download/0.5.4/uv-x86_64-apple-darwin.tar.gz", lazy = true }

[[lift.files]]
name = "uv-macos-aarch64"
key = "uv-aarch64-apple-darwin"
type = "tar.gz"
digest = { size = 81373, fingerprint = "0b1bb612e4beff00ba7da9bb46402219ba42062e1fdcb31529ddeb97251186cb" }
source = { url = "https://github.com/astral-sh/uv/releases/download/0.5.4/uv-aarch64-apple-darwin.tar.gz", lazy = true }

[[lift.files]]
name = "uv-linux-x86_64"
key = "uv-x86_64-unknown-linux-gnu"
type = "tar.gz"
digest = { size = 14486696, fingerprint = "c5b63d1cd0a894246195250c034f9d82d646dc8f718f1f424cec2bb1a42e7b17" }
source = { url = "https://github.com/astral-sh/uv/releases/download/0.5.4/uv-x86_64-unknown-linux-gnu.tar.gz", lazy = true }

##################################################################
################### process compose #####
[[lift.files]]
name = "process-compose-macos-x86_64"
type = "tar.gz"
digest = { size = 81373, fingerprint = "8ee85c5c569a9efc554a12a89adc9ca676233de4346a42e48646219d65923338" }
source = { url = "https://github.com/F1bonacc1/process-compose/releases/download/v1.40.1/process-compose_darwin_amd64.tar.gz", lazy = true }

[[lift.files]]
name = "process-compose-macos-aarch64"
type = "tar.gz"
digest = { size = 81373, fingerprint = "0b1bb612e4beff00ba7da9bb46402219ba42062e1fdcb31529ddeb97251186cb" }
source = { url = "https://github.com/F1bonacc1/process-compose/releases/download/v1.40.1/process-compose_darwin_armd64.tar.gz", lazy = true }

[[lift.files]]
name = "process-compose-linux-x86_64"
type = "tar.gz"
digest = { size = 81373, fingerprint = "2122033a7d18c08e998e51f1aa9380b49369e662482e60b1045b468441dba55c" }
source = { url = "https://github.com/F1bonacc1/process-compose/releases/download/v1.40.1/process-compose_linux_amd64.tar.gz", lazy = true }

##################################################################
################### EASYRSA ######################################
[[lift.files]]
name = "easyrsa"
type = "tar.gz"
digest = { size = 79917, fingerprint = "ec0fdca46c07afef341e0e0eeb2bf0cfe74a11322b77163e5d764d28cb4eec89" }
source = { url = "https://github.com/OpenVPN/easy-rsa/releases/download/v3.2.1/EasyRSA-3.2.1.tgz", lazy = true }


#[[lift.files]]
#name = "caddy"
#type = "tar.gz"
#digest = { size = 14655532, fingerprint = "99587cf77c595f0bf62cc23c9ea101f9879fa016c7b689d498ce054904821f22" }
#source = { url = "https://github.com/caddyserver/caddy/releases/download/v2.7.6/caddy_2.7.6_linux_amd64.tar.gz", lazy = true }

#"{scie.platform}",

##################################################################
################### Boot #########################################
[[lift.commands]]
description = "Detects the current PikeSquares installation and launches it."
exe = "{scie-pikesquares.bin}"

##################################################################
################### Run PikeSquares ##############################
[[lift.commands]]
name = "pikesquares"
# No description because this command shouldn't render in the help output (it's invoked as
# appropriate by the default "Boot" one above)
# description = "Runs a hermetic PikeSquares installation."
exe = "{scie.bindings.install:PIKESQUARES_SERVER_EXE}"

[lift.commands.env.default]
PIKESQUARES_PROCESS_COMPOSE_DIR = "{process-compose-{scie.platform}}" 
PIKESQUARES_VERSION = "{scie.bindings.configure:PIKESQUARES_VERSION}"
PIKESQUARES_DATA_DIR = "{scie.bindings.install:PIKESQUARES_DATA_DIR}"
PIKESQUARES_VIRTUAL_ENV = "{scie.bindings.install:VIRTUAL_ENV}"
PIKESQUARES_BUILDROOT_OVERRIDE = "{scie.bindings.configure:PIKESQUARES_BUILDROOT_OVERRIDE}"
PIKESQUARES_SCIE_BINDINGS = "{scie.bindings}"
PIKESQUARES_EASYRSA_DIR = "{easyrsa}"
PIKESQUARES_EASYRSA_BIN = "{easyrsa}/EasyRSA-3.2.1/easyrsa"
PIKESQUARES_SENTRY_DSN = "123"
PIKESQUARES_PYTHON_BIN = "#{cpython:python}"
PIKESQUARES_UWSGI_BIN = "{uwsgi/uwsgi}"
#PC_PORT_NUM = "9555"
#CADDY_DIR = "{caddy}"

#[lift.commands.env.replace]
#_PIKESQUARES_SERVER_EXE = "{scie.bindings.install:PIKESQUARES_SERVER_EXE}"
#PEX_ROOT = "{scie.bindings}/pex_root"
#PEX_PYTHON_PATH = "#{cpython:python}"

##################################################################
################### process-compose    ###########################
[[lift.commands]]
name = "process-compose-up"
description = "Launch process manager"
exe = "{process-compose-{scie.platform}}/process-compose"
# {scie.file.<name>}
# {scie.file.{env.var.FILE_NAME}}
args = [
  "up",
  "--config",
  "{scie.bindings.install:PIKESQUARES_DATA_DIR}/process-compose.yml",
  "--detached",
]
[lift.commands.env.default]
PIKESQUARES_VERSION = "{scie.bindings.configure:PIKESQUARES_VERSION}"
PIKESQUARES_PYTHON_BIN = "{scie.bindings.install:VIRTUAL_ENV}/bin/python"
#PIKESQUARES_PYTHON_BIN = "#{cpython:python}"
PIKESQUARES_SERVER_EXE = "{scie.bindings.install:PIKESQUARES_SERVER_EXE}"
PIKESQUARES_DATA_DIR = "{scie.bindings.install:PIKESQUARES_DATA_DIR}"
PIKESQUARES_CONFIG_DIR = "{scie.bindings.install:PIKESQUARES_CONFIG_DIR}"
PIKESQUARES_LOG_DIR = "{scie.bindings.install:PIKESQUARES_LOG_DIR}"
PIKESQUARES_BUILDROOT_OVERRIDE = "{scie.bindings.configure:PIKESQUARES_BUILDROOT_OVERRIDE}"
PIKESQUARES_SCIE_BINDINGS = "{scie.bindings}"
PIKESQUARES_EASYRSA_DIR = "{easyrsa}"
PIKESQUARES_EASYRSA_BIN = "{easyrsa}/EasyRSA-3.2.1/easyrsa"
PIKESQUARES_SENTRY_DSN = "123"
PIKESQUARES_UWSGI_BIN = "{uwsgi/uwsgi}"
PC_PORT_NUM = "9555"
#CADDY_DIR = "{caddy}"

[[lift.commands]]
name = "process-compose-attach"
description = "Launch process manager"
exe = "{process-compose-{scie.platform}}/process-compose"
args = ["attach"]

[lift.commands.env.default]
PIKESQUARES_VERSION = "{scie.bindings.configure:PIKESQUARES_VERSION}"
PIKESQUARES_PYTHON_BIN = "{scie.bindings.install:VIRTUAL_ENV}/bin/python"
#PIKESQUARES_PYTHON_BIN = "#{cpython:python}"
PIKESQUARES_SERVER_EXE = "{scie.bindings.install:PIKESQUARES_SERVER_EXE}"
PIKESQUARES_DATA_DIR = "{scie.bindings.install:PIKESQUARES_DATA_DIR}"
PIKESQUARES_LOG_DIR = "{scie.bindings.install:PIKESQUARES_LOG_DIR}"
PIKESQUARES_BUILDROOT_OVERRIDE = "{scie.bindings.configure:PIKESQUARES_BUILDROOT_OVERRIDE}"
PIKESQUARES_SCIE_BINDINGS = "{scie.bindings}"
PIKESQUARES_EASYRSA_DIR = "{easyrsa}"
PIKESQUARES_EASYRSA_BIN = "{easyrsa}/EasyRSA-3.2.1/easyrsa"
PIKESQUARES_SENTRY_DSN = "123"
PC_PORT_NUM = "9555"
#CADDY_DIR = "{caddy}"

[[lift.commands]]
name = "process-compose-down"
description = "Launch process manager"
exe = "{process-compose-{scie.platform}}/process-compose"
args = ["down"]

[lift.commands.env.default]
PIKESQUARES_VERSION = "{scie.bindings.configure:PIKESQUARES_VERSION}"
PIKESQUARES_PYTHON_BIN = "{scie.bindings.install:VIRTUAL_ENV}/bin/python"
PIKESQUARES_SERVER_EXE = "{scie.bindings.install:PIKESQUARES_SERVER_EXE}"
PIKESQUARES_DATA_DIR = "{scie.bindings.install:PIKESQUARES_DATA_DIR}"
PIKESQUARES_LOG_DIR = "{scie.bindings.install:PIKESQUARES_LOG_DIR}"
PIKESQUARES_BUILDROOT_OVERRIDE = "{scie.bindings.configure:PIKESQUARES_BUILDROOT_OVERRIDE}"
PIKESQUARES_SCIE_BINDINGS = "{scie.bindings}"
PIKESQUARES_EASYRSA_DIR = "{easyrsa}"
PIKESQUARES_EASYRSA_BIN = "{easyrsa}/EasyRSA-3.2.1/easyrsa"
PIKESQUARES_SENTRY_DSN = "123"
PC_PORT_NUM = "9555"
#CADDY_DIR = "{caddy}"

##################################################################
################### Bootstrap Tools
[[lift.commands]]
name = "bootstrap-tools"
description = "Introspection tools for the PikeSquares bootstrap process."
exe = "#{cpython:python}"
args = [
    "{tools.pex}",
    "bootstrap-tools",
    "--python-distribution-hash",
    "{scie.files:hash.#{cpython}}",
    "--pikesquares-version",
    "{scie.bindings.configure:PIKESQUARES_VERSION}",
]
env.remove_re = [
    "PEX_.*",
]

[lift.commands.env.replace]
PEX_ROOT = "{scie.bindings}/pex_root"
PEX_PYTHON_PATH = "#{cpython:python}"


##################################################################
################### Configure PikeSquares
[[lift.bindings]]
name = "configure"
description = "Configure PikeSquares"
exe = "#{cpython:python}"
args = [
    "{tools.pex}",
    "configure-pikesquares",
    "--ptex-path",
    "{ptex}",
    "--pikesquares-version",
    "{scie.env.PIKESQUARES_VERSION}",
    "{scie.bindings}",
]
env.remove_re = [
    "PEX_.*",
]

[lift.bindings.env.default]
PIKESQUARES_VERSION_PROMPT_SALT = "{scie.env.PIKESQUARES_VERSION_PROMPT_SALT}"

PIKESQUARES_UV_BIN = "{uv-{scie.platform}}/uv-{scie.platform.arch}-unknown-{scie.platform.os}-gnu/uv"

#PIKESQUARES_UV_BIN = "{uv-{scie.platform}}/{scie.file./uv"

# scie.os - macos linux
# scie.arch - x86_64 aarch64
# scie.platform - macos-x86_64 linux-x86_64 macos-aarch64

# uv-macos-x86_64/uv-x86_64-apple-darwin/
# uv-linux-x86_64/uv-x86_64-unknown-linux-gnu
# uv-macos-aarch64/uv-aarch64-apple-darwin/

SCIE_LIFT_FILE = "{scie.lift}"
PIKESQUARES_PYTHON_BIN = "#{cpython:python}"


#[lift.bindings.env.replace]
#PEX_ROOT = "{scie.bindings}/pex_root"
#PEX_PYTHON_PATH = "#{cpython:python}"

##################################################################
################### Install PikeSquares
[[lift.bindings]]
name = "install"
description = """\
Installs a hermetic PikeSquares environment from a GitHub release \
"""
exe = "#{cpython:python}"
args = [
    "{tools.pex}",
    "install-pikesquares",
    "--pikesquares-version",
    "{scie.bindings.configure:PIKESQUARES_VERSION}",
    "--ptex-path",
    "{ptex}",
    "--localdev-dir",
    "{scie.bindings.configure:PIKESQUARES_LOCALDEV_DIR}",
    "{scie.bindings}",
]
env.remove_re = [
    "PEX_.*",
]

[lift.bindings.env.default]
SCIE_LIFT_FILE = "{scie.lift}"
# uv-x86_64-unknown-linux-gnu
# uv-aarch64-apple-darwin
# uv-x86_64-apple-darwin
#PIKESQUARES_UV_BIN = "{uv-{scie.platform}}/uv-{scie.platform.arch}-unknown-{scie.platform.os}-gnu/uv"
PIKESQUARES_UV_ROOT = "{uv-{scie.platform}}"
PIKESQUARES_PYTHON_BIN = "#{cpython:python}"
UV_PYTHON = "#{cpython:python}"
#{process-compose-{scie.platform}}

#[lift.bindings.env.replace]
#PEX_ROOT = "{scie.bindings}/pex_root"
#PEX_PYTHON_PATH = "#{cpython:python}"

##################################################################
################### Self Update
[[lift.commands]]
name = "update"
description = "Update scie-pikesquares."
exe = "#{cpython:python}"
args = [
    "{tools.pex}",
    "update-scie-pikesquares",
    "--ptex-path",
    "{ptex}",
    "--platform",
    "{scie.platform}",
    "--base-dir",
    "{scie.bindings}",
    "--scie",
    "{scie}",
    "--current-version",
    "{scie.bindings.scie-pikesquares-info:VERSION}",
    "--github-api-bearer-token",
    "{scie.env.PIKESQUARES_BOOTSTRAP_GITHUB_API_BEARER_TOKEN}",
]
env.remove_re = [
    "PEX_.*",
]

[lift.commands.env.replace]
PEX_ROOT = "{scie.bindings}/pex_root"
PEX_PYTHON_PATH = "#{cpython:python}"

##################################################################
################### Self Info
[[lift.bindings]]
name = "scie-pikesquares-info"
description = "Records information about the current scie-pikesquares binary."
exe = "#{cpython:python}"
args = [
    "{tools.pex}",
    "record-scie-pikesquares-info",
    "--base-dir",
    "{scie.bindings}",
    "--scie",
    "{scie}",
]
env.remove_re = [
    "PEX_.*",
]

[lift.bindings.env.replace]
PEX_ROOT = "{scie.bindings}/pex_root"
PEX_PYTHON_PATH = "#{cpython:python}"


