[lift]
name = "scie-pikesquares"
description = "PikeSquares isolation."
#base = "{scie.env.SCIE_BASE:/var/lib/pikesquares}"
load_dotenv = true

[lift.app_info]
repo = "https://github.com/eloquentbits/scie-pikesquares"

[lift.ptex]
id = "ptex"
version = "1.2.0"
argv1 = "{scie.env.PIKESQUARES_BOOTSTRAP_URLS={scie.lift}}"

[lift.scie_jump]
version = "1.2.0"

[[lift.interpreters]]
id = "cpython"
provider = "PythonBuildStandalone"
release = "20241002"
lazy = true
version = "3.12.7"

#[[lift.interpreters]]
#id = "cpython39"
#provider = "PythonBuildStandalone"
#release = "20241007"
#lazy = true
#version = "3.9.18"

#[[lift.interpreter_groups]]
#id = "cpython"
#selector = "{scie.bindings.configure:PYTHON}"
#members = [
#    "cpython39",
#    "cpython312",
#]

[[lift.files]]
# N.B.: We name the scie-pikesquares binary scie-pikesquares.bin since the scie itself is named scie-pikesquares
# which would conflict when packaging.
name = "scie-pikesquares.bin"

[[lift.files]]
name = "tools.pex"

[[lift.files]]
name = "easyrsa"
type = "tar.gz"
digest = { size = 81373, fingerprint = "aaa48fadcbb77511b9c378554ef3eae09f8c7bc149d6f56ba209f1c9bab98c6e" }
source = { url = "https://github.com/OpenVPN/easy-rsa/releases/download/v3.1.7/EasyRSA-3.1.7.tgz", lazy = true }


[[lift.files]]
name = "caddy"
type = "tar.gz"
digest = { size = 14655532, fingerprint = "99587cf77c595f0bf62cc23c9ea101f9879fa016c7b689d498ce054904821f22" }
source = { url = "https://github.com/caddyserver/caddy/releases/download/v2.7.6/caddy_2.7.6_linux_amd64.tar.gz", lazy = true }

#"{scie.platform}",

# Boot
[[lift.commands]]
description = "Detects the current PikeSquares installation and launches it."
exe = "{scie-pikesquares.bin}"

# Run PikeSquares
[[lift.commands]]
name = "pikesquares"
# No description because this command shouldn't render in the help output (it's invoked as
# appropriate by the default "Boot" one above)
# description = "Runs a hermetic PikeSquares installation."
exe = "{scie.bindings.install:PIKESQUARES_SERVER_EXE}"

[lift.commands.env.default]
PIKESQUARES_BUILDROOT_OVERRIDE = "{scie.bindings.configure:PIKESQUARES_BUILDROOT_OVERRIDE}"
PIKESQUARES_SCIE_BINDINGS = "{scie.bindings}"
#PIKESQUARES_EASYRSA_DIR = "{easyrsa}"
CADDY_DIR = "{caddy}"

[lift.commands.env.replace]
PIKESQUARES_VERSION = "{scie.bindings.configure:PIKESQUARES_VERSION}"
_PIKESQUARES_SERVER_EXE = "{scie.bindings.install:PIKESQARES_SERVER_EXE}"
PIKESQUARES_DATA_DIR = "{scie.bindings.install:PIKESQUARES_DATA_DIR}"

PEX_ROOT = "{scie.bindings}/pex_root"
PEX_PYTHON_PATH = "#{cpython:python}"

# Bootstrap Tools
[[lift.commands]]
name = "bootstrap-tools"
description = "Introspection tools for the PikeSquares bootstrap process."
exe = "#{cpython:python}"
args = [
    "{tools.pex}",
    "bootstrap-tools",
    "--python-distribution-hash",
    "{scie.files:hash.#{cpython}}",
    "--pikesquares-version",
    "{scie.bindings.configure:PIKESQUARES_VERSION}",
]
env.remove_re = [
    "PEX_.*",
]

[lift.commands.env.replace]
PEX_ROOT = "{scie.bindings}/pex_root"
PEX_PYTHON_PATH = "#{cpython:python}"

# Configure PikeSquares
[[lift.bindings]]
name = "configure"
description = "Configure PikeSquares"
exe = "#{cpython:python}"
args = [
    "{tools.pex}",
    "configure-pikesquares",
    "--ptex-path",
    "{ptex}",
    "--pikesquares-version",
    "{scie.env.PIKESQUARES_VERSION}",
    "{scie.bindings}",
]
env.remove_re = [
    "PEX_.*",
]

[lift.bindings.env.default]
PIKESQUARES_VERSION_PROMPT_SALT = "{scie.env.PIKESQUARES_VERSION_PROMPT_SALT}"

[lift.bindings.env.replace]
PEX_ROOT = "{scie.bindings}/pex_root"
PEX_PYTHON_PATH = "#{cpython:python}"

# Install PikeSquares
[[lift.bindings]]
name = "install"
description = """\
Installs a hermetic PikeSquares environment from a GitHub release \
"""
exe = "#{cpython:python}"
args = [
    "{tools.pex}",
    "install-pikesquares",
    "--pikesquares-version",
    "{scie.bindings.configure:PIKESQUARES_VERSION}",
    "--ptex-path",
    "{ptex}",
    "--localdev-dir",
    "{scie.bindings.configure:PIKESQUARES_LOCALDEV_DIR}",
    "{scie.bindings}",
]
env.remove_re = [
    "PEX_.*",
]

[lift.bindings.env.replace]
PEX_ROOT = "{scie.bindings}/pex_root"
PEX_PYTHON_PATH = "#{cpython:python}"

# Self Update
[[lift.commands]]
name = "update"
description = "Update scie-pikesquares."
exe = "#{cpython:python}"
args = [
    "{tools.pex}",
    "update-scie-pikesquares",
    "--ptex-path",
    "{ptex}",
    "--platform",
    "{scie.platform}",
    "--base-dir",
    "{scie.bindings}",
    "--scie",
    "{scie}",
    "--current-version",
    "{scie.bindings.scie-pikesquares-info:VERSION}",
    "--github-api-bearer-token",
    "{scie.env.PIKESQUARES_BOOTSTRAP_GITHUB_API_BEARER_TOKEN}",
]
env.remove_re = [
    "PEX_.*",
]

[lift.commands.env.replace]
PEX_ROOT = "{scie.bindings}/pex_root"
PEX_PYTHON_PATH = "#{cpython:python}"

# Self Info
[[lift.bindings]]
name = "scie-pikesquares-info"
description = "Records information about the current scie-pikesquares binary."
exe = "#{cpython:python}"
args = [
    "{tools.pex}",
    "record-scie-pikesquares-info",
    "--base-dir",
    "{scie.bindings}",
    "--scie",
    "{scie}",
]
env.remove_re = [
    "PEX_.*",
]

[lift.bindings.env.replace]
PEX_ROOT = "{scie.bindings}/pex_root"
PEX_PYTHON_PATH = "#{cpython:python}"


